import{a,S as y,i as c}from"./assets/vendor-145b7b72.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="live_fgu8iS6wymqhXDmI8v5efK6dfuAQbMhu9CJZc761AlQip0E7bIdGEACcOH4rXg1T";a.defaults.headers.common["x-api-key"]=E;function w(){return a.get("https://api.thecatapi.com/v1/breeds")}function b(t){return a.get("https://api.thecatapi.com/v1/images/search",{params:{breed_ids:t}})}const i={selectEl:document.querySelector(".breed-select"),catInfoEl:document.querySelector(".cat-info"),loaderEl:document.querySelector(".loader")};d(i.loaderEl);const v=new y({select:i.selectEl,settings:{allowDeselect:!0},events:{beforeChange:(t,r)=>{var s,n;d(i.loaderEl),b(((s=t[0])==null?void 0:s.value)||((n=r[0])==null?void 0:n.value)).then(({data:e})=>{var o,l,u,p,f,h,m;if(e.length){i.catInfoEl.innerHTML=S({url:(o=e[0])==null?void 0:o.url,name:(u=(l=e[0])==null?void 0:l.breeds[0])==null?void 0:u.name,desc:(f=(p=e[0])==null?void 0:p.breeds[0])==null?void 0:f.description,temp:(m=(h=e[0])==null?void 0:h.breeds[0])==null?void 0:m.temperament});return}i.catInfoEl.innerHTML="",c.show({title:"Error",message:"Oops! Something went wrong! Try other one!",color:"red",position:"topRight"})}).catch(e=>{c.show({title:"Error",message:"Oops! Something went wrong! Try other one!",color:"red",position:"topRight"})}).finally(()=>{g(i.loaderEl)})},error:function(t){console.log("error-->",t),c.show({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",color:"red",position:"topRight"})}}});w().then(({data:t})=>{const r=t.map(({name:s,id:n})=>({text:s,value:n}));v.setData(r),d(i.selectEl)}).catch(t=>{c.show({title:"Error",message:"Oops! Something went wrong! Try reloading the page!",color:"red",position:"topRight"})}).finally(()=>{g(i.loaderEl)});function S({url:t,name:r,desc:s,temp:n}){return`
      <img src="${t}" alt="${r}" width="500" />
      <div class="">
        <h2>${r}</h2>
        <p>${s}</p>
        <p>Temperaments: <span style="font-weight: bold;">${n}</span></p>
      </div>
      `}function d(t){t.classList.remove("hidden")}function g(t){t.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
